# Generated by Django 4.0.2 on 2022-04-04 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import middleware.current_user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectAchievementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('s_id', models.CharField(db_index=True, max_length=4, verbose_name='学号')),
                ('maths', models.IntegerField(null=True, verbose_name='高等数学')),
                ('english', models.IntegerField(null=True, verbose_name='大学英语')),
                ('physics', models.IntegerField(null=True, verbose_name='大学物理')),
                ('computer_networks', models.IntegerField(null=True, verbose_name='计算机网络')),
                ('c_language', models.IntegerField(null=True, verbose_name='C语言')),
                ('data_structure', models.IntegerField(null=True, verbose_name='数据结构')),
                ('computer', models.IntegerField(null=True, verbose_name='计算机组成原理')),
                ('network_programming', models.IntegerField(null=True, verbose_name='网络编程')),
                ('network_security', models.IntegerField(null=True, verbose_name='网络安全')),
                ('result', models.IntegerField(choices=[('1', '合格'), ('0', '不合格'), ('2', '待审核'), ('3', '待上传')], default=2, null=True, verbose_name='是否合格')),
                ('created_by', models.ForeignKey(default=middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('s_id', models.CharField(db_index=True, max_length=4, verbose_name='学号')),
                ('subject_result', models.IntegerField(choices=[('1', '合格'), ('0', '不合格'), ('2', '待审核'), ('3', '待上传')], default=2, null=True, verbose_name='学生学科成绩审核结果')),
                ('overall_result', models.IntegerField(choices=[('1', '合格'), ('0', '不合格'), ('2', '待审核'), ('3', '待上传')], default=2, null=True, verbose_name='学生综合素质审核结果')),
                ('design_result', models.IntegerField(choices=[('1', '合格'), ('0', '不合格'), ('2', '待审核'), ('3', '待上传')], default=2, null=True, verbose_name='学生课程设计成绩审核结果')),
                ('final_result', models.IntegerField(choices=[('1', '审核通过'), ('0', '审核不通过'), ('2', '待审核'), ('3', '成绩待上传')], default=2, null=True, verbose_name='最终审核结果')),
                ('created_by', models.ForeignKey(default=middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentOverallQualityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('s_id', models.CharField(db_index=True, max_length=4, verbose_name='学号')),
                ('community_activities', models.IntegerField(null=True, verbose_name='课外活动学分')),
                ('sports', models.IntegerField(null=True, verbose_name='体育成绩')),
                ('physical_test', models.IntegerField(null=True, verbose_name='身体素质测试')),
                ('computer_grade_exams', models.IntegerField(null=True, verbose_name='计算机等级考试')),
                ('english_grade_exams', models.IntegerField(null=True, verbose_name='英语等级考试')),
                ('result', models.IntegerField(choices=[('1', '合格'), ('0', '不合格'), ('2', '待审核'), ('3', '待上传')], default=2, null=True, verbose_name='是否合格')),
                ('created_by', models.ForeignKey(default=middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('s_id', models.CharField(db_index=True, max_length=4, verbose_name='学号')),
                ('s_name', models.CharField(max_length=50, null=True, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, null=True, verbose_name='性别')),
                ('ethnic', models.CharField(max_length=50, null=True, verbose_name='民族')),
                ('political_a', models.CharField(max_length=50, null=True, verbose_name='政治面貌')),
                ('homeland', models.CharField(max_length=255, null=True, verbose_name='生源地')),
                ('birthday', models.DateTimeField(null=True, verbose_name='生日')),
                ('id_no', models.CharField(max_length=50, null=True, verbose_name='身份证号')),
                ('qq', models.CharField(max_length=50, null=True, verbose_name='QQ号')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='电话号码')),
                ('data_status', models.IntegerField(choices=[(11, '正常'), (12, '删除')], default=11, null=True, verbose_name='数据状态')),
                ('created_by', models.ForeignKey(default=middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StudentCourseDesignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('s_id', models.CharField(db_index=True, max_length=4, verbose_name='学号')),
                ('linux', models.IntegerField(null=True, verbose_name='linux课设')),
                ('c', models.IntegerField(null=True, verbose_name='c语言课设')),
                ('java', models.IntegerField(null=True, verbose_name='java课设')),
                ('python', models.IntegerField(null=True, verbose_name='python课设')),
                ('web', models.IntegerField(null=True, verbose_name='前端课设')),
                ('graduation_design', models.IntegerField(null=True, verbose_name='毕业设计')),
                ('result', models.IntegerField(choices=[('1', '合格'), ('0', '不合格'), ('2', '待审核'), ('3', '待上传')], default=2, null=True, verbose_name='是否合格')),
                ('created_by', models.ForeignKey(default=middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
